#pragma once

namespace GUIEditor::Utils {
	enum ElementsIDs {
		SELECT_GUI_ELEMENT_PROPEERTY_GRID = 0x99,
		ADD_WINDOW,
		ADD_BUTTON,
		ADD_IMAGE,
		ADD_LABLE,
		ADD_TEXTBOX,
		ADD_CHECKBOX,
		ADD_LISTBOX,
		GUI_EDITOR_ADD_VIEW,
		GUI_EDITOR_SAVE_VIEW,
		GUI_EDITOR_REMOVE_VIEW,
		GUI_EDITOR_OPEN_VIEW,
		USE_GRID_CHECKBOX,
		GUI_EDITOR_CANVAS,
	};
}