#pragma once

#define PATH_PROPERTY_TITLE L"Path"
#define POSITION_PROPERTY_TITLE L"Position"
#define TEXT_PROPERTY_TITLE L"Text"
#define NAME_PROPERTY_TITLE L"Name"
#define OPTIONS_PROPERTY_TITLE L"Options"

#define GUI_EDITOR_ELEMENTS_PAGE_TITLE L"On screen"
#define GUI_EDITOR_ADDING_ELEMENTS_TITLE L"Adding elements"
#define GUI_EDITOR_DRAW_GRID_CHECKBOX L"Draw grid"

#define GUI_EDITOR_WINDOW_TOOLS_MENU_ADD L"Add"
#define GUI_EDITOR_WINDOW_TOOLS_MENU_REMOVE L"Remove"
#define GUI_EDITOR_WINDOW_TOOLS_MENU_SAVE L"Save"
#define GUI_EDITOR_WINDOW_TOOLS_MENU_OPEN L"Open"